version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    networks:
      - network
    ports:
      - ${CLIENT_PORT}:80
    depends_on:
      - server
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    volumes:
      - ./${EMAILS_DIR}:/app/${EMAILS_DIR}
    networks:
      - network
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${PROFILING_PORT}:${PROFILING_PORT}
    depends_on:
      - zinc
    restart: on-failure

  zinc:
    image: public.ecr.aws/zinclabs/zinc:latest
    volumes:
      - zinc-data:/data
    networks:
      - network
    env_file:
      - .env
    environment:
      - GIN_MODE=release
    ports:
      - ${ZINC_SERVER_PORT}:${ZINC_SERVER_PORT}
    restart: unless-stopped

volumes:
  zinc-data: {}

networks:
  network:
    driver: bridge
