version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    restart: unless-stopped
