version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    networks:
      - network
    # env_file:
    #   - .env
    # environment:
    #   - VITE_INDEX_NAME=${VITE_INDEX_NAME}
    #   - VITE_BASE_URI=${VITE_BASE_URI}
    ports:
      - ${CLIENT_PORT}:80
    depends_on:
      - server
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    volumes:
      - ./${EMAILS_DIR}:/app/${EMAILS_DIR}
    networks:
      - network
    env_file:
      - .env
    environment:
      - ENABLE_PROFILING=${ENABLE_PROFILING}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${PROFILING_PORT}:${PROFILING_PORT}
    depends_on:
      - zinc
    restart: on-failure

  zinc:
    image: public.ecr.aws/zinclabs/zinc:latest
    volumes:
      - zinc-data:/data
    networks:
      - network
    environment:
      - ZINC_FIRST_ADMIN_USER=${ZINC_ADMIN_USER}
      - ZINC_FIRST_ADMIN_PASSWORD=${ZINC_ADMIN_PASSWORD}
      - ZINC_SERVER_PORT=${ZINC_PORT}
      - ZINC_DATA_PATH=/data
      - GIN_MODE=release
    ports:
      - ${ZINC_PORT}:${ZINC_PORT}
    restart: unless-stopped

volumes:
  zinc-data: {}

networks:
  network:
    driver: bridge
